---
name: "Build smqtk for python 3.6"
type: docker
kind: pipeline

platform:
  os: linux
  arch: amd64

steps:
  - name: "Build smqtk python 3.6"
    image: python:3.6
    commands:
      - git clean -xdf
      - apt-get update && apt-get -y install cmake
      - pip3 install -r requirements.txt -r requirements.test.txt
      - mkdir build
      - cd build
      - CMAKE_INSTALL_PREFIX="$(realpath $(dirname $(which python3))/..)"
      - cmake -DSMQTK_BUILD_FLANN:BOOL=OFF
              -DSMQTK_PIP_INSTALL_FLAGS:STRING="-e"
              -DCMAKE_BUILD_TYPE:STRING=DEBUG
              -DCMAKE_INSTALL_PREFIX:STRING="$CMAKE_INSTALL_PREFIX"
              ..
      - make -j$(nproc) install
      - cd ..
      - python3 setup.py test

trigger:
  event:
    - pull_request

---
name: "Build smqtk for python 3.7"
type: docker
kind: pipeline

platform:
  os: linux
  arch: amd64

steps:
  - name: "Build smqtk python 3.7"
    image: python:3.7
    commands:
      - git clean -xdf
      - apt-get update && apt-get -y install cmake
      - pip3 install -r requirements.txt -r requirements.test.txt
      - mkdir build
      - cd build
      - CMAKE_INSTALL_PREFIX="$(realpath $(dirname $(which python3))/..)"
      - cmake -DSMQTK_BUILD_FLANN:BOOL=OFF
              -DSMQTK_PIP_INSTALL_FLAGS:STRING="-e"
              -DCMAKE_BUILD_TYPE:STRING=DEBUG
              -DCMAKE_INSTALL_PREFIX:STRING="$CMAKE_INSTALL_PREFIX"
              ..
      - make -j$(nproc) install
      - cd ..
      - python3 setup.py test

trigger: 
  event:
    - pull_request

---
name: "Build smqtk for python 3.8"
type: docker
kind: pipeline

platform:
  os: linux
  arch: amd64

steps:
  - name: "Build smqtk python 3.8"
    image: python:3.8
    commands:
      - git clean -xdf
      - apt-get update  && apt-get -y install cmake
      - pip3 install -r requirements.txt -r requirements.test.txt
      - mkdir build
      - cd build
      - CMAKE_INSTALL_PREFIX="$(realpath $(dirname $(which python3))/..)"
      - cmake -DSMQTK_BUILD_FLANN:BOOL=OFF
              -DSMQTK_PIP_INSTALL_FLAGS:STRING="-e"
              -DCMAKE_BUILD_TYPE:STRING=DEBUG
              -DCMAKE_INSTALL_PREFIX:STRING="$CMAKE_INSTALL_PREFIX"
              ..
      - make -j$(nproc) install
      - cd ..
      - python3 setup.py test
      
trigger: 
  event:
    - pull_request
