version: "3.4"

services:

  #
  # TPL providing images.
  #

  tpl-caffe-base:
    # Base stage for common use by CPU and GPU build variants.
    image: ${SMQTK_REGISTRY}/tpl-caffe:1.0-base
    build:
      context: tpl/caffe1
      target: base
      args:
        CUDA_DEVEL_IMAGE_TAG:  # using value from .env file.

  tpl-caffe-cpu:
    # CPU-Only build variant
    image: ${SMQTK_REGISTRY}/tpl-caffe:1.0-cpu
    depends_on:
      - tpl-caffe-base
    build:
      context: tpl/caffe1
      target: caffe_cpu
      args:
        CUDA_DEVEL_IMAGE_TAG:  # using value from .env file.

  tpl-caffe-gpu:
    # GPU build variant
    image: ${SMQTK_REGISTRY}/tpl-caffe:1.0-cuda${CUDA_DEVEL_IMAGE_TAG}
    depends_on:
      - tpl-caffe-base
    build:
      context: tpl/caffe1
      target: caffe_gpu
      args:
        CUDA_DEVEL_IMAGE_TAG:  # using value from .env file.
        # One or more CUDA architecture binary versions to compile for.
        CUDA_ARCH_BIN_LIST: 35 52 60 61 62

  tpl-faiss-gpu:
    image: ${SMQTK_REGISTRY}/tpl-faiss:${FAISS_VERSION}-cuda${CUDA_DEVEL_IMAGE_TAG}
    build:
      context: tpl/faiss
      dockerfile: gpu/Dockerfile
      args:
        FAISS_VERSION:  # using value from .env file.
        CUDA_DEVEL_IMAGE_TAG:  # using value from .env file.
        # One or more CUDA architectures to compile for.
        # Using ">-" for multi-line string concatenation with no new-lines.
        CUDA_ARCH: >-
          -gencode=arch=compute_35,code=compute_35
          -gencode=arch=compute_52,code=compute_52
          -gencode=arch=compute_60,code=compute_60
          -gencode=arch=compute_61,code=compute_61
          -gencode=arch=compute_62,code=compute_62

  iqr-playground-gpu:
    image: ${SMQTK_REGISTRY}/iqr_playground:latest-gpu-cuda8-cudnn6
    depends_on:
      - bvlc-caffe-gpu
    build:
      # Repo root
      context: ../..
      dockerfile: devops/docker/smqtk_iqr_playground/Dockerfile.gpu-cuda8.0-cudnn6.df
