"""
LICENCE
-------
Copyright 2013 by Kitware, Inc. All Rights Reserved. Please refer to
KITWARE_LICENSE.TXT for licensing information, or contact General Counsel,
Kitware, Inc., 28 Corporate Drive, Clifton Park, NY 12065.

"""

import os
import string
import re


def get_regex_sun_attributes():
    """ Generates Regular Expression to parse filenames for sun attribute feature files.
    Parses a filename such as HVC000029_sec_+1_x2_000002.jpg.sun_attributes.txt.

    Usage: regex = get_regex_sun_attributes(); match = regex.match(str); print match.groupdict()
    """

    pattern = 'HVC(?P<clipid>\d+)_(?P<unit>sec|frame)_(?:[+](?P<offset>\d+)_)?x(?P<multiplier>\d+)_(?P<idx>\d+).\w'
    regex = re.compile(pattern)
    return regex

def parse_sun_attributes(filename):
    """Parse filename generated by SUN ATTRIBUTE code

    Parses a filename such as HVC000029_sec_+1_x2_000002.jpg.sun_attributes.txt.

    """

    _filename = os.path.basename(filename)
    regex = get_regex_sun_attributes()
    matches = regex.match(_filename)

    return matches.groupdict()
